### ISSUE TITLE
Not getting broadcast message on my google home mini, while in My Activity got entries showing it broadcasted

### ISSUE THREAD

**Issue by singhvaibhav98** [ismarslomic/google-assistant-broadcast#12] opened 2023-05-16 05:00 UTC
Hi,
I am able to generate auth and also able to hit the broadcast message and it is reaching to my activity but not hearing any sound on home mini speaker, I tried deleted all the devices and re-added in action console and also tried changing the language as suggested but it didn't work.

![image](https://github.com/ismarslomic/google-assistant-broadcast/assets/38852017/973ea87b-e4e1-4cff-85a6-cf3c60c62e9e)

![image](https://github.com/ismarslomic/google-assistant-broadcast/assets/38852017/851e55ef-1085-4252-a3c7-29b456cbc971)

I also tried setting APPEND_BROADCAST_TO_MESSAGE to false and then used below broadcast message
{
    "message": "Broadcast to bedroom speaker, Hello world."
}

My speaker is set to high volume as well. 

Please help,

**Comment by ismarslomic** [comment] 2023-05-18 17:59
@singhvaibhav98 Im not able to reproduce this issue and Im using this solution every day. So it seems to be a local problem at your end, which I can't reproduce on my side and thus hardly support you further. It is not easy to debug errors with Google Assistant, as you can see from the [closed issues](https://github.com/ismarslomic/google-assistant-broadcast/issues?q=is%3Aissue+is%3Aclosed).

Be also aware of that Home Assistant now supports broadcasting to Google Assistant without interrupting the music, by use of [Google Assistant SDK](https://www.home-assistant.io/integrations/google_assistant_sdk) integration. I would advice you to take a look at it.

Closing the issue.

**Closed as completed by ismarslomic** 2023-05-18 17:59 UTC
