### ISSUE TITLE
Broadcast does not go to speakers - did I do the oauth config right?

### ISSUE THREAD

**Issue by flecmart** [ismarslomic/google-assistant-broadcast#11] opened 2022-10-20 21:52 UTC
Hi,

this seems like a nice litle solution to integrate broadcasting for non disruptive tts notifications in home assitant - thank you :-) 

I tried to setup your solution but I got the same problems as described in #9 #5 #7.

I am pretty confident with js and docker so that setup was no problem for me but I am quite confused about the oauth setup - I used your oauth docker to get the token from the client_secret and I followed the instructions - but I am not sure If I did everything right? 

The documentation in https://github.com/ismarslomic/google-assistant-oauth

- **Google OAuth 2.0 Client ID** - in order to authenticate yourself and get access to your Google
  Assistant.
    - Follow steps **1-5**
      in [Configure an Actions Console project](https://developers.google.com/assistant/sdk/guides/service/python/embed/config-dev-project-and-account)
    - Make sure that you choose **"Device registration"** when creating new project in **Actions
      Console**
    - **!Important!** Download the OAuth Client file from GCP Console / API & Services / Credentials page (not from Google Actions Console), read solution on issue [#7](https://github.com/ismarslomic/google-assistant-broadcast/issues/7#issuecomment-1151601639). Make also sure that the `Application type` of the OAuth Client is `Desktop`
    - Rename the downloaded file **from** `client_secret_****.apps.googleusercontent.com.json` **to** `client_secret.json`

is actually quite confusing for me. In the link to issue #7 there is something about readding a device model - but I did not find anything about adding this in the first place? It is not clear how to obtain the correct client_secret for me. Also - where do I configure which speakers the broadcast goes to? Does the Google Assistant sdk automatically detect my google home minis linked to my google account?

Sorry for all the questions - I'd love to use this.

**Comment by ismarslomic** [comment] 2022-12-06 18:45
@flecmart sorry for delayed reply. Currently I have not found a solution where you can broadcast a message to specific speakers. The message is broadcasted to all speakers you have configured in your Google Assistant (app).

In regards to the issue discussed in #7, I have added an extra validation of the content from file `client_secret.json` as part of the Docker container, see https://github.com/ismarslomic/google-assistant-broadcast/commit/3423b2bbffd420e1152801ad63aee00cdadba8a7. So if you don't see any validation errors, then your file content is correct.

Since the root cause in #5 and #9 was never identified, I'm not able to tell what the solution is. I'm running this solution every day, and it has been stable for many months now without exception. So it's not easy to reproduce the issue and support you.

However, could you try running the docker containers on other machine, maybe your own desktop/laptop?

**Comment by flecmart** [comment] 2022-12-07 10:01
Thanks for your reply. So if I got no validation erros I can assume I did the oauth steps correct? Then I don't know what else to try... I allready tried different machines - a rasperry pi4 and my windows dekstop machine. If someone finds the solution for #5 or #9 I might come back and try it again :-)

**Comment by ismarslomic** [comment] 2023-01-03 23:47
Closing the issue. I hope you managed to fix it!

**Closed as completed by ismarslomic** 2023-01-03 23:47 UTC
